### ISSUE TITLE
Support for server icons

### ISSUE THREAD

**Issue by Akarys42** [gustavwilliam/branding-bot#3]
It would be nice to have a command to retrieve server icons, like user profile pictures. Lookup could be done by ID or by invite, defaulting to the current server if any.

**Comment by gustavwilliam** [comment]
Good idea!

Would you like to implement it? Otherwise I'll have a look at what's possible myself.

I imagine that the command would be called `/discord server_icon` with the optional arguments `server_id` (or `id`?) and `invite`. Only one of the arguments should be specified.

**Comment by vivekashok1221** [comment]
I'm interested in implementing this.

PS: I feel `id` will suffice.

**Comment by gustavwilliam** [comment]
Sounds great! Tell me if there's anything you need help with 😄

**Comment by vivekashok1221** [comment]
Thanks. What do you envisage should happen if a person provides both `id` and `invite` parameters?

**Comment by gustavwilliam** [comment]
Either throw an error or prioritise `id`. What do you think?
